version: 2.1
orbs:
  ruby: circleci/ruby@1.2.0

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.3
    steps:
      - checkout
      - ruby/install-deps
  lint:
    docker:
      - image: cimg/ruby:2.7.3
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check:
          format: progress
          label: Inspecting with Rubocop
  test:
    docker:
      - image: cimg/ruby:2.7.3
      - image: cimg/postgres:11.5-alpine-ram
        environment:
          POSTGRES_DB: stocks_and_bearers_test
          POSTGRES_PASSWORD: ''
          POSTGRES_USER: test
    environment:
      BUNDLE_JOBS: '3'
      BUNDLE_RETRY: '3'
      PGHOST: 127.0.0.1
      PGPASSWORD: ''
      PGUSER: test
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - run:
          command: 'dockerize -wait tcp://localhost:5432 -timeout 1m'
          name: Wait for DB
      - run:
          command: 'bundle exec rails db:schema:load --trace'
          name: Database setup
      - ruby/rspec-test

workflows:
  CI:
    jobs:
      - build
      - lint
      - test:
          requires:
            - build
