openapi: 3.0.0
info:
  title: Stocks and Bearers
  version: '1.0'
  summary: This api shows how I built APIs using Ruby on Rails
  description: |-
    The API contains mostly two enitites Stock and Bearer. Where stocks might be created with a referenced bearer, updated and listed. The bearers might be created and updated.
    The API uses JSON api specification.
  contact:
    name: Ilgam
    url: 'https://github.com/IlkhamGaysin'
  license:
    name: MIT
    url: 'https://spdx.org/licenses/MIT.html'
servers:
  - url: 'https://stocks-and-bearers-staging.herokuapp.com'
    description: Staging
  - description: Production
    url: 'https://stocks-and-bearers-production.herokuapp.com'
paths:
  /v1/stocks:
    post:
      summary: ''
      operationId: post-v1-stocks
      responses:
        '201':
          description: ''
          content:
            application/vnd.api+json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    data:
                      type: stocks
                      id: 550e8400-e29b-41d4-a716-446655440000
                      attributes:
                        name: Apple
                properties:
                  data:
                    type: object
                    required:
                      - type
                      - id
                      - attributes
                    properties:
                      type:
                        type: string
                        minLength: 1
                        enum:
                          - stocks
                        example: stocks
                      id:
                        type: string
                        minLength: 1
                        format: uuid
                      attributes:
                        type: object
                        required:
                          - name
                        properties:
                          name:
                            type: string
                            minLength: 1
                required:
                  - data
              examples:
                example-1:
                  value:
                    data:
                      type: stocks
                      id: 17235511-9621-4f84-b2ad-021ae86f4fb3
                      attributes:
                        name: Apple
      description: Endpoint to create a stock with a referenced bearer
      parameters:
        - schema:
            type: string
            example: application/vnd.api+json
            enum:
              - application/vnd.api+json
          in: header
          name: Content-Type
          description: application/vnd.api+json
          required: true
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              description: ''
              type: object
              x-examples:
                example-1:
                  data:
                    type: photos
                    attributes:
                      title: Ember Hamster
                      src: 'http://example.com/images/productivity.png'
                    relationships:
                      photographer:
                        data:
                          type: people
                          id: '9'
              properties:
                data:
                  type: object
                  required:
                    - type
                    - attributes
                    - relationships
                  properties:
                    type:
                      type: string
                      minLength: 1
                      enum:
                        - stocks
                      example: stocks
                    attributes:
                      type: object
                      required:
                        - name
                        - src
                      properties:
                        name:
                          type: string
                          minLength: 1
                        src:
                          type: string
                          minLength: 1
                    relationships:
                      type: object
                      description: Key to specify relations to a stock
                      required:
                        - bearer
                      properties:
                        bearer:
                          type: object
                          required:
                            - data
                          properties:
                            data:
                              type: object
                              required:
                                - type
                                - id
                              properties:
                                type:
                                  type: string
                                  minLength: 1
                                  pattern: bearer
                                  description: It defines relation name used on backend to identify which type assign to.
                                  enum:
                                    - bearer
                                  example: bearer
                                id:
                                  type: string
                                  minLength: 1
                                  description: The uid of a bearer to connect to
                                  example: 0468dfd2-6255-458a-842d-10db27f1fae0
                                  format: uuid
              required:
                - data
    get:
      summary: ''
      operationId: get-v1-stocks
      responses:
        '200':
          description: ''
          content:
            application/vnd.api+json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    data:
                      - type: stocks
                        id: 0468dfd2-6255-458a-842d-10db27f1fae0
                        attributes:
                          name: Apple
                        relationships:
                          bearer:
                            data:
                              type: bearer
                              id: 1727d4e3-b5d7-4a59-8992-67c6897d130d
                              attributes:
                                name: John
                      - type: stocks
                        id: 284b4532-59e6-45a7-98c4-59ee36aa5f00
                        attributes:
                          name: Microsoft
                        relationships:
                          bearer:
                            data:
                              type: bearer
                              id: 1727d4e3-b5d7-4a59-8992-67c6897d130d
                              attributes:
                                name: John
                      - type: stocks
                        id: 284b4532-59e6-45a7-98c4-59ee36aa5f00
                        attributes:
                          name: NVIDIA
                        relationships:
                          bearer:
                            data:
                              type: bearer
                              id: 9ca9b0b5-ce3a-4c28-b556-30606c531b87
                              attributes:
                                name: Pieter
                properties:
                  data:
                    type: array
                    uniqueItems: true
                    minItems: 0
                    items:
                      type: object
                      description: Primary data of a stock
                      properties:
                        type:
                          type: string
                          minLength: 1
                          example: stocks
                          enum:
                            - stocks
                        id:
                          type: string
                          minLength: 1
                          example: 975f81b3-7721-473c-a166-4e75f3564be8
                          format: uuid
                        attributes:
                          type: object
                          properties:
                            name:
                              type: string
                              minLength: 1
                          required:
                            - name
                        relationships:
                          type: object
                          properties:
                            bearer:
                              type: object
                              required:
                                - data
                              properties:
                                data:
                                  type: object
                                  required:
                                    - type
                                    - id
                                    - attributes
                                  properties:
                                    type:
                                      type: string
                                      minLength: 1
                                      description: It defines relation name used on backend
                                      enum:
                                        - bearers
                                      example: bearers
                                    id:
                                      type: string
                                      minLength: 1
                                      description: The uid of a bearer stock owned by
                                      example: 284b4532-59e6-45a7-98c4-59ee36aa5f00
                                      format: uuid
                                    attributes:
                                      type: object
                                      required:
                                        - name
                                      description: Represent attributes a particular bearer without id
                                      properties:
                                        name:
                                          type: string
                                          minLength: 1
                          required:
                            - bearer
                      required:
                        - type
                        - id
                required:
                  - data
              examples:
                example-1:
                  value:
                    data:
                      - type: stocks
                        id: 0468dfd2-6255-458a-842d-10db27f1fae0
                        attributes:
                          name: Apple
                        relationships:
                          bearer:
                            data:
                              type: bearer
                              id: 1727d4e3-b5d7-4a59-8992-67c6897d130d
                              attributes:
                                name: John
                      - type: stocks
                        id: 284b4532-59e6-45a7-98c4-59ee36aa5f00
                        attributes:
                          name: Microsoft
                        relationships:
                          bearer:
                            data:
                              type: bearer
                              id: 1727d4e3-b5d7-4a59-8992-67c6897d130d
                              attributes:
                                name: John
                      - type: stocks
                        id: 284b4532-59e6-45a7-98c4-59ee36aa5f00
                        attributes:
                          name: NVIDIA
                        relationships:
                          bearer:
                            data:
                              type: bearer
                              id: 9ca9b0b5-ce3a-4c28-b556-30606c531b87
                              attributes:
                                name: Pieter
      description: Endpoint to list all stocks with bearers
      parameters:
        - schema:
            type: string
            enum:
              - application/vnd.api+json
            example: application/vnd.api+json
          in: header
          name: Content-Type
          description: application/vnd.api+json
          required: true
    put:
      summary: ''
      operationId: put-v1-stocks
      responses:
        '200':
          description: ''
          content:
            application/vnd.api+json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    data:
                      type: stocks
                      id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                      attributes:
                        name: Tesla
                properties:
                  data:
                    type: object
                    required:
                      - type
                      - id
                      - attributes
                    properties:
                      type:
                        type: string
                        minLength: 1
                        enum:
                          - stocks
                        example: stocks
                      id:
                        type: string
                        minLength: 1
                        format: uuid
                      attributes:
                        type: object
                        required:
                          - name
                        properties:
                          name:
                            type: string
                            minLength: 1
                required:
                  - data
              examples:
                example-1:
                  value:
                    data:
                      type: stocks
                      id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                      attributes:
                        name: Tesla
      parameters:
        - schema:
            type: string
            enum:
              - application/vnd.api+json
            example: application/vnd.api+json
          in: header
          name: Content-Type
          description: application/vnd.api+json
          required: true
      description: Endpoint to update a stock. Bearer that owns a stock can't be updated here.
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              description: ''
              type: object
              x-examples:
                example-1:
                  data:
                    type: stocks
                    id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                    attributes:
                      name: Tesla
              properties:
                data:
                  type: object
                  required:
                    - type
                    - id
                    - attributes
                  properties:
                    type:
                      type: string
                      minLength: 1
                      example: stocks
                      enum:
                        - stocks
                    id:
                      type: string
                      minLength: 1
                      format: uuid
                    attributes:
                      type: object
                      required:
                        - name
                      properties:
                        name:
                          type: string
                          minLength: 1
              required:
                - data
            examples:
              example-1:
                value:
                  data:
                    type: stocks
                    id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                    attributes:
                      name: Tesla
        description: ''
components:
  schemas:
    Stock:
      title: Stock
      type: object
      description: This represents stock that is being using by bearers
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          example: 'John '
      required:
        - id
        - name
    Bearer:
      title: Bearer
      type: object
      description: This represents a person who owns stock/s
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          example: Apple
      required:
        - id
        - name
  securitySchemes: {}
